#!/bin/sh
/etc/init.d/haveged enable
/etc/init.d/haveged start

. /lib/ar71xx.sh
. /lib/freifunk/lib_node.sh

sysname="$(uci get system.@system[0].hostname)"
uci -q batch <<EOF
	set system.@system[0].hostname="$(get_node_id)"
	set system.@system[0].timezone='CET-1CEST,M3.5.0,M10.5.0/3'
	set freifunk.@node[0].nodeid="$(get_node_id)"
	delete system.ntp.server
	add_list system.ntp.server='2a01:4f8:d13:4a85::2'
	add_list system.ntp.server='2a00:1828:2000:115::2'
	add_list system.ntp.server='1.openwrt.pool.ntp.org'
	add_list system.ntp.server='2.openwrt.pool.ntp.org'
	add_list system.ntp.server='1.ntp.kbu.freifunk.net'
	add_list system.ntp.server='2.ntp.kbu.freifunk.net'	

	commit system
	commit freifunk
EOF

