#!/bin/sh

uci -q batch <<EOF
        add firewall zone
        set firewall.@zone[-1].forward=REJECT
        set firewall.@zone[-1].input=REJECT
        set firewall.@zone[-1].mtu_fix=1
        set firewall.@zone[-1].name=Freifunk
        set firewall.@zone[-1].network=freifunk
        set firewall.@zone[-1].output=ACCEPT
                   
        commit firewall
 
EOF

